Check manifest presence after build

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -38,3 +38,8 @@ echo "-----> bundle exec rake webpack:compile"
 bundle exec rake webpack:compile --trace
 echo "-----> npm prune"
 npm prune
+
+if [ ! -s $1/public/client/manifest.json ]; then
+  echo "Can't find manifest.json. Build failed"
+  exit 1
+fi
